data:
  salary:  "data/salary.csv"
  brent:   "data/brent.csv"

experiment:
  horizons: [1, 24, 168, 365]
  cv_folds: rolling
  metrics: [rmse, mase, smape, dm]

models:
  naive:
    lang: [python, r, julia]
  seasonal_naive:
    lang: [python, r, julia]
  ets:
    lang: [python, r, julia]
  auto_arima:
    lang: [python, r, julia]
